# Generated by Django 4.2.3 on 2023-07-22 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_congratulation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Congratulation',
            new_name='Comment',
        ),
    ]
