# Generated by Django 4.2.3 on 2023-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=None),
        ),
    ]
