# Generated by Django 4.2.3 on 2023-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
